# Generic, formatter-friendly config.
select = ["B", "D3", "E", "F"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
#ignore = ["E501","S101","ruff/E402","bandit/B101","B101"]
ignore = ["E501","S101","ruff/E402"]
